### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [eReuse/desktop-app#5]
Please provide the AppImage for download on GitHub Releases, thanks.
Possibly you might be interested in https://github.com/probonopd/uploadtool which simplifies this.

Reference:
AppImage/AppImageHub#15

**Comment by jnadeu** [comment]
We'll finish a first version for next week. We only provide deb package because we work with Debian distributions and we need to install Workbench's dependencies (diagnostic tool). 
Thank you for share uploadtool.
